server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_blog_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    druid:
      min-idle: 5
      initial-size: 20
      max-active: 30
      max-wait: 30000
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 200000

custom:
  my-blog:
    captcha:
      text-producer-font-color: black
      text-producer-char-space: 5
      text-producer-font-size: 30
      image-width: 150
      image-height: 40
      session-key: verifyCode
      border: 'no'